server {
    listen 80;
    server_name _;

    location = /.well-known/matrix/client {
        default_type application/json;
        add_header Access-Control-Allow-Origin "*" always;
        return 200 '{"m.homeserver":{"base_url":"https://matrix.celesteai.ru"}}';
    }

    location = /.well-known/matrix/server {
        default_type application/json;
        return 200 '{"m.server":"matrix.celesteai.ru:443"}';
    }

    location = /.well-known/matrix/support {
        default_type application/json;
        return 404;
    }

    location / {
        return 404;
    }
}
